// <auto-generated />
namespace BM_Solution.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Update_DuAnUser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update_DuAnUser));
        
        string IMigrationMetadata.Id
        {
            get { return "201710021035027_Update_DuAnUser"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
